# ---------------------------------
# Settings for the baseline method.
#
# author: An Tran
# affiliation: Tampere University
# ---------------------------------
model: !include model_ht_12_37.yaml
# ----------------------
data:
  input_field_name: 'features'
  output_field_name: 'words_ind'
  load_into_memory: No
  batch_size: 1 
  shuffle: Yes
  num_workers: 2
  drop_last: Yes
  use_multiple_mode: No
  use_validation_split: No
# ----------------------
training:
  batch_by_batch: Yes
  lwf_weight: 0.7
  evaluate_after_each: Yes
  nb_epochs: 300
  patience: 50
  loss_thr: !!float 1e-2
  optimizer:
    lr: !!float 1e-4
  grad_norm:
    value: !!float 1.
    norm: 2
  force_cpu: No
  text_output_every_nb_epochs: !!int 10
  nb_examples_to_sample: 100
  use_y: Yes
  clamp_value_freqs: -1  # -1 is for ignoring
  # EOF

